title: Nora Cook - Data Science Portfolio
description: Showcase of my data science projects.
MS Business Analytics Candidate @ CSUEB | Specialized in Environmental Data Science
Oakland, California 
email: noralbc606@gmail.com 
phone: (510)325-9296 
https://www.linkedin.com/in/nora-cookie/
logo: 1762065830391.jpeg
remote_theme: pages-themes/minimal@v0.2.0
