# Site Settings
title: "Nora Cook - Data Science Portfolio"
description: "Showcase of my data science projects."
bio: "MS Business Analytics Candidate @ CSUEB | Specialized in Environmental Data Science"
location: "Oakland, California"

# Contact & Social Media Info
email: "noralbc606@gmail.com"
phone: "(510) 325-9296"
linkedin: "https://www.linkedin.com/in/nora-cookie/"

# Theme & Assets
remote_theme: pages-themes/minimal@v0.2.0
logo: "/assets/images/1762065830391.jpeg"
